# SPDX-FileCopyrightText: Copyright Contributors to the GXF project
#
# SPDX-License-Identifier: Apache-2.0

# SPRING CONFIGURATION
spring:
  application:
    name: gxf-publiclighting-message-transformer

  artemis:
    broker-url: tcp://localhost:61616
    user: "artemis"
    password: "artemis"
    pool:
      enabled: true
      max-connections: 10

# MODULE CONFIGURATION
device-events:
  enabled: true
  consumer:
    inbound-queue: device-events.inbound.DEV
    min-concurrency: 2
    max-concurrency: 10
  producer:
    outbound-queue: device-events.outbound.DEV
    quality-of-service:
      explicit-qos-enabled: true    # enable the use of deliveryMode, priority, and timeToLive
      delivery-persistent: true     # whether messages are persistent or non-persistent
      priority: 4                   # value between 0 (lowest) and 9 (highest), default is 4
      time-to-live: 0               # time to live in milliseconds, 0 means messages never expire

device-message-logs:
  enabled: true
  inbound-queue: device-message-logs.inbound.DEV
  outbound-queue: device-message-logs.outbound.DEV

device-requests:
  enabled: true
  inbound-queue: device-requests.inbound.DEV
  outbound-queue: device-requests.outbound.DEV

device-responses:
  enabled: true
  inbound-queue: device-responses.inbound.DEV
  outbound-queue: device-responses.outbound.DEV
