# SPDX-FileCopyrightText: Copyright Contributors to the GXF project
#
# SPDX-License-Identifier: Apache-2.0

spring:
  application:
    name: gxf-publiclighting-message-transformer

  artemis:
    mode: native
    broker-url: tcp://localhost:61616
    user: "artemis"
    password: "artemis"
    pool:
      enabled: true

  jms:
    listener:
      session:
        transacted: false

  main:
    web-application-type: none

management:
  endpoint:
    health:
      probes:
        enabled: true
  server:
    port: 9080

# MODULE CONFIGURATIONS
common:
  messaging:
    deserialization-policy:
      whitelist:
        - org.lfenergy.gxf.*
        - com.alliander.gxf.*
        - java.util.*
        - java.datetime.*

device-events:
  enabled: true
  consumer:
    inbound-queue: device-events.inbound.IT
    min-concurrency: 2
    max-concurrency: 10
  producer:
    outbound-queue: device-events.outbound.IT
    quality-of-service:
      explicit-qos-enabled: true    # enable the use of deliveryMode, priority, and timeToLive
      delivery-persistent: true     # whether messages are persistent or non-persistent
      priority: 4                   # value between 0 (lowest) and 9 (highest), default is 4
      time-to-live: 0               # time to live in milliseconds, 0 means messages never expire

device-message-logs:
  enabled: true
  inbound-queue: device-message-logs.inbound.IT
  outbound-queue: device-message-logs.outbound.IT

device-requests:
  enabled: true
  inbound-queue: device-requests.inbound.IT
  outbound-queue: device-requests.outbound.IT

device-responses:
  enabled: true
  inbound-queue: device-responses.inbound.IT
  outbound-queue: device-responses.outbound.IT
